### ISSUE TITLE
Router with basename "build" is already registered. Please provide a unique basename for viewset "<class 'squad.api.rest.BuildViewSet'>"

### ISSUE THREAD

**Issue by Nagendra-AlifSemi** [Linaro/squad#1133]
I am trying to install SQUAD in Debian 12(bookworm) by taking reference of this Doc : label[https://squad.readthedocs.io/en/latest/install.html#production-install-ref-label](url). I could able to install all the packages as mentioned.

**But when i launch squad :** $ ~/.local/bin/squad
Traceback (most recent call last):
  File "/home/nagendra/.local/bin/squad", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/squad/run/__init__.py", line 50, in main
    manage()
  File "/home/nagendra/.local/lib/python3.11/site-packages/squad/manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nagendra/.local/lib/python3.11/site-packages/squad/urls.py", line 86, in <module>
    url(r'^api/', include('squad.api.urls')),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nagendra/.local/lib/python3.11/site-packages/squad/api/urls.py", line 8, in <module>
    from . import rest
  File "/home/nagendra/.local/lib/python3.11/site-packages/squad/api/rest.py", line 1890, in <module>
    router.register(r'builds', BuildViewSet).register(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/rest_framework_extensions/routers.py", line 57, in register
    self._register(*args, **kwargs)
  File "/home/nagendra/.local/lib/python3.11/site-packages/rest_framework_extensions/routers.py", line 54, in _register
    return super().register(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.local/lib/python3.11/site-packages/rest_framework/routers.py", line 59, in register
    raise ImproperlyConfigured(msg)
**django.core.exceptions.ImproperlyConfigured: Router with basename "build" is already registered. Please provide a unique basename for viewset "<class 'squad.api.rest.BuildViewSet'>"**

thanks,
Nagendra S

**Comment by chaws** [comment]
Hi @Nagendra-AlifSemi thanks for raising this issue.

It is fixed in release https://github.com/Linaro/squad/releases/tag/v1.84.

Can you please try it again?

**Comment by Nagendra-AlifSemi** [comment]
Hi @chaws ,
I have cleaned up the packs of squad 1.83 & installed latest version squad v1.84  [https://squad.readthedocs.io/en/latest/install.html]
I have afraid to say still leads to another issue:
(.venv) nagendra@Nagendra-Debain:~$ squad
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, ci, contenttypes, core, django_celery_results, sessions, sites, socialaccount
Running migrations:
  No migrations to apply.
Post-processing 'angularjs/angular-resource.min.js' failed!

Traceback (most recent call last):
  File "/home/nagendra/.venv/bin/squad", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nagendra/.venv/lib/python3.11/site-packages/squad/run/__init__.py", line 52, in main
    manage()
  File "/home/nagendra/.venv/lib/python3.11/site-packages/squad/manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "/home/nagendra/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/nagendra/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nagendra/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nagendra/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nagendra/.venv/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
                ^^^^^^^^^^^^^^
  File "/home/nagendra/.venv/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
**whitenoise.storage.MissingFileError: The file 'angularjs/angular-resource.min.js.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fd8f84cac90>.**

**The JS file 'angularjs/angular-resource.min.js' references a file which could not be found:
  angularjs/angular-resource.min.js.map**

**Please check the URL references in this JS file, particularly any
relative paths which might be pointing to the wrong location.**

squad installed successfully but unable to launch:
(.venv) nagendra@Nagendra-Debain:~$ squad --version
**squad (version 1.84)**
(.venv) nagendra@Nagendra-Debain:~$ lsb
lsblk        lsb_release  
(.venv) nagendra@Nagendra-Debain:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
(.venv) nagendra@Nagendra-Debain:~$

**Comment by Nagendra-AlifSemi** [comment]
Above issue is fixed with this change in squad settings.py (*/python3.11/site-packages/squad/settings.py). I am able to launch squad with v1.84 (production). 
modified STATICFILES_STORAGE:
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  default_code
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

<img width="682" alt="squad_1 84_after_fix" src="https://github.com/Linaro/squad/assets/87651860/1952011a-a9b6-4a02-9a1b-5b7d3e9a3a56">

Appreciated for your support . 

Thanks ,

Regards
Nagendra S

**Comment by chaws** [comment]
Good to know you got that working @Nagendra-AlifSemi !
I'll close this issue now

**Comment by Nagendra-AlifSemi** [comment]
looks like Compare builds("No tests to display") issue also might be resolved in latest version.
