### ISSUE TITLE
KeyError: 'error_type' when fetching LAVA job

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#308]
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]: Traceback (most recent call last):
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/celery/app/trace.py", line 374, in trace_task
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:     R = retval = fun(*args, **kwargs)
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/celery/app/trace.py", line 629, in __protected_call__
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:     return self.run(*args, **kwargs)
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/ci/tasks.py", line 31, in fetch
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:     test_job.backend.fetch(test_job)
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/ci/models.py", line 78, in fetch
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:     self.really_fetch(test_job)
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/ci/models.py", line 86, in really_fetch
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:     results = implementation.fetch(test_job)
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/ci/backend/lava.py", line 63, in fetch
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:     return self.__parse_results__(data, test_job) + (logs,)
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/ci/backend/lava.py", line 328, in __parse_results__
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]:     if metadata['error_type'] in ['Infrastructure', 'Lava', 'Job']:
Jul 12 17:17:02 qa-reports-worker-0 celery[6083]: KeyError: 'error_type'

**Comment by mwasilew** [comment]
Fixed with #310
