### ISSUE TITLE
Double submission results in error

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#6]
When submitting the same data twice, 2 TestRun objects are created. This results in the following exception in the UI:

```
Internal Server Error: /lcr/android-lcr-reference-x15-n/build/52/testrun/1324766/
Traceback (most recent call last):
  File "/home/milosz/linaro/tcstorm/squad/squad-venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/milosz/linaro/tcstorm/squad/squad-venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/milosz/linaro/tcstorm/squad/squad-venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/milosz/linaro/tcstorm/squad/squad-venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/milosz/linaro/tcstorm/squad/squad-venv/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/milosz/linaro/tcstorm/squad/squad/frontend/views.py", line 81, in test_run
    test_run = build.test_runs.get(job_id=job_id)
  File "/home/milosz/linaro/tcstorm/squad/squad-venv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/milosz/linaro/tcstorm/squad/squad-venv/lib/python3.5/site-packages/django/db/models/query.py", line 389, in get
    (self.model._meta.object_name, num)
squad.core.models.MultipleObjectsReturned: get() returned more than one TestRun -- it returned 2!
```

I guess the proper action is to add data to the existing TestRun if all other details are matching.

**Comment by terceiro** [comment]
in which case would a double submission make sense?

**Comment by mwasilew** [comment]
Double submission of the exact same data makes no sense (at least to me). But I think it's a good idea to have ability to add tests to the same TestRun. In case of LAVA this probably isn't the case as each job is processed separately and TestRun == LAVA test job. But there might be other cases.

For the moment it would be enough to just prevent double submission. In my case it was a forgotten queue process doing strange things.
