### ISSUE TITLE
Handle incomplete response from LAVA

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#786]
Fetch task crashes when LAVA is not responding properly for download logs request.

```
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]: [2020-07-08 19:29:51 +0000] [WARNING] validation.linaro.org: Logs for job 2054231 are not available
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]: Traceback (most recent call last):
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 685, in _update_chunk_length
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:     self.chunk_left = int(line, 16)
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]: ValueError: invalid literal for int() with base 16: b''
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]: During handling of the above exception, another exception occurred:
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]: Traceback (most recent call last):
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 425, in _error_catcher
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:     yield
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 752, in read_chunked
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:     self._update_chunk_length()
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 689, in _update_chunk_length
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:     raise httplib.IncompleteRead(line)
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]: http.client.IncompleteRead: IncompleteRead(0 bytes read)
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]: During handling of the above exception, another exception occurred:
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]: Traceback (most recent call last):
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/models.py", line 750, in generate
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:     for chunk in self.raw.stream(chunk_size, decode_content=True):
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 560, in stream
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:     for line in self.read_chunked(amt, decode_content=decode_content):
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 781, in read_chunked
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:     self._original_response.close()
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:   File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:     self.gen.throw(type, value, traceback)
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 443, in _error_catcher
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:     raise ProtocolError("Connection broken: %r" % e, e)
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]: urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]: During handling of the above exception, another exception occurred:
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]: Traceback (most recent call last):
Jul 08 19:29:51 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/ci/backend/lava.py", line 58, in fetch
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:     raw_logs = BytesIO(self.__download_full_log__(test_job.job_id))
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/ci/backend/lava.py", line 282, in __download_full_log__
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:     response = requests.get(url, params=payload)
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/api.py", line 75, in get
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:     return request('get', url, params=params, **kwargs)
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/api.py", line 60, in request
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:     return session.request(method=method, url=url, **kwargs)
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:     resp = self.send(prep, **send_kwargs)
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/sessions.py", line 686, in send
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:     r.content
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/models.py", line 828, in content
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:     self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/models.py", line 753, in generate
Jul 08 19:29:52 qa-reports-worker-1 squad-worker[27278]:     raise ChunkedEncodingError(e)
```

**Comment by chaws** [comment]
Fixed in https://github.com/Linaro/squad/pull/790
