### ISSUE TITLE
Handle broken pipe LAVA REST

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#789]
It looks like when there's a case like "lkft.validation.linaro.org: Logs for job 1562942 are not available" that apparently is causing the worker to stall forever. Celery seems to log the stack trace fine but it doesn't seem to recover from it.

**Comment by mwasilew** [comment]
We're not using REST in any of the backends yet.

**Comment by mwasilew** [comment]
this is the traceback:
```
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]: Traceback (most recent call last):
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 685, in _update_chunk_length
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     self.chunk_left = int(line, 16)
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]: ValueError: invalid literal for int() with base 16: b''
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]: During handling of the above exception, another exception occurred:
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]: Traceback (most recent call last):
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 425, in _error_catcher
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     yield
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 752, in read_chunked
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     self._update_chunk_length()
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 689, in _update_chunk_length
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     raise httplib.IncompleteRead(line)
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]: http.client.IncompleteRead: IncompleteRead(0 bytes read)
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]: During handling of the above exception, another exception occurred:
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]: Traceback (most recent call last):
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/models.py", line 750, in generate
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     for chunk in self.raw.stream(chunk_size, decode_content=True):
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 560, in stream
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     for line in self.read_chunked(amt, decode_content=decode_content):
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 781, in read_chunked
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     self._original_response.close()
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     self.gen.throw(type, value, traceback)
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/urllib3/response.py", line 443, in _error_catcher
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     raise ProtocolError("Connection broken: %r" % e, e)
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]: urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]: During handling of the above exception, another exception occurred:
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]: Traceback (most recent call last):
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/ci/backend/lava.py", line 58, in fetch
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     raw_logs = BytesIO(self.__download_full_log__(test_job.job_id))
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/ci/backend/lava.py", line 282, in __download_full_log__
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     response = requests.get(url, params=payload)
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/api.py", line 75, in get
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     return request('get', url, params=params, **kwargs)
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/api.py", line 60, in request
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     return session.request(method=method, url=url, **kwargs)
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     resp = self.send(prep, **send_kwargs)
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/sessions.py", line 686, in send
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     r.content
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/models.py", line 828, in content
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:   File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/requests/models.py", line 753, in generate
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]:     raise ChunkedEncodingError(e)
Jul 16 08:44:38 qa-reports-worker-1 squad-worker[31754]: requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```
It happens when LAVA closes connection during log file download.
