### ISSUE TITLE
Units not always present in LAVA measurements

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#892]
```
[2020-11-02 16:53:40 +0000] [ERROR] Task squad.ci.tasks.fetch[2a0f7521-8402-48f6-ba04-3041b2498a6d] raised unexpected: KeyError('unit')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/squad/celery.py", line 28, in __call__
    return super(MemoryUseLoggingTask, self).__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/integrations/celery.py", line 169, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/integrations/celery.py", line 164, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/squad/ci/tasks.py", line 29, in fetch
    backend.fetch(job_id)
  File "/usr/local/lib/python3.7/dist-packages/squad/ci/models.py", line 80, in fetch
    results = self.get_implementation().fetch(test_job)
  File "/usr/local/lib/python3.7/dist-packages/squad/ci/backend/lava.py", line 117, in fetch
    return self.__parse_results__(data, test_job, raw_logs)
  File "/usr/local/lib/python3.7/dist-packages/squad/ci/backend/lava.py", line 586, in __parse_results__
    unit = result['unit']
KeyError: 'unit'
```

**Comment by mwasilew** [comment]
This happens when using REST API for LAVA. The underlying issue is that in REST there is 'units' key instead of 'unit'. We need a temporary fix for this in SQUAD.

When using REST API there is also inconsistency on how the suite is presented which should also be addressed with the patch.

**Comment by chaws** [comment]
Fixed in https://github.com/Linaro/squad/pull/895
