### ISSUE TITLE
Worker stuck after backend server timed out

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#967]
Plugin postprocessing error: HTTPSConnectionPool(host='validation.linaro.org', port=443): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  F...

After this error the worker got stuck idling and prevented the autoscaler from adding extra workers and the queue was stuck as well

**Comment by chaws** [comment]
While there's no actual fix for this, the PR https://github.com/Linaro/squad/pull/971 fixes the issue that caused too much memory being allocated,  which eventually causes workers to get stuck. I'm closing this. 

Just for reference, the real bug is described here: https://chaws.me/en/linux/kubernetes/2020/08/07/aws-eks-fargate-bug.html

But it's out of our reach to really fix it
