### ISSUE TITLE
Fix testing on real LAVA

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#990]
Testing with LAVA containers are failing:

```python
Setup the database
/usr/lib/python3/dist-packages/environ/environ.py:615: UserWarning: /usr/lib/python3/dist-packages/lava_server/settings/.env doesn't exist - if you're not configuring your environment separately, create one.
  "environment separately, create one." % env_file)
Create database:
Traceback (most recent call last):
  File "/usr/share/lava-server/postinst.py", line 326, in <module>
    sys.exit(main())
  File "/usr/share/lava-server/postinst.py", line 321, in main
    create_database(config)
  File "/usr/share/lava-server/postinst.py", line 76, in create_database
    db = config["DATABASES"]["default"]["NAME"]
KeyError: 'default'

```

**Comment by chaws** [comment]
@bhcopeland could you send the PR about moving squad to github actions?

**Comment by chaws** [comment]
It seems the LAVA issue has been fixed here: https://git.lavasoftware.org/lava/lava/-/commit/ae746fd5c6ff23599c0d7f51d670b35fc4093b47
